### ISSUE TITLE
WARNING:root:You are using the default load_mask(), maybe you need to define your own one.

### ISSUE THREAD

**Issue by Beezai** [AarohiSingla/Mask-R-CNN-on-Custom-Dataset#5]
Hi Aarohi,

I am getting this warning, its coming continuously without going to next epoch.
Would you please help me to address this warning.

thank you.

**Comment by IdentifyResearchAreasandGoals** [comment]
Hi Aarohi,
I am getting " AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"


How to solve

**Comment by IdentifyResearchAreasandGoals** [comment]
I solve
thanks
